#!/bin/bash

sudo wget -O /var/www/html/wp.tar.gz https://wordpress.org/latest.tar.gz
sudo tar xf /var/www/html/wp.tar.gz -C /var/www/html/
sudo rm /var/www/html/wp.tar.gz -r
sudo cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
sudo sed 's/database_name_here/wordpress/' -i /var/www/html/wordpress/wp-config.php
sudo sed 's/username_here/wpdbadmin/' -i /var/www/html/wordpress/wp-config.php
sudo sed 's/password_here/Nick4321/' -i /var/www/html/wordpress/wp-config.php
sudo sed 's/localhost/wordpressdb.cajcuoq985li.us-west-1.rds.amazonaws.com/' -i /var/www/html/wordpress/wp-config.php
sudo sed '/Directory \"\/var\/www\/html/,/AllowOverride None/s/AllowOverride None/AllowOverride All/' -i /etc/httpd/conf/httpd.conf
sudo groupadd www
sudo usermod -a -G www apache
sudo chown -R apache:www /var/www
sudo chmod 2775 /var/www
sudo find /var/www -type d -exec chmod 2775 {} \;
sudo find /var/www -type f -exec chmod 0664 {} \;
sudo systemctl restart httpd.service
